scope: zabbix
namespace: /db/
name: node2

etcd3:
  hosts:
      - NODE1-IP:2379
      - NODE2-IP:2379
      - NODE3-IP:2379

bootstrap:
  dcs:
    ttl: 30
    retry_timeout: 10

    postgresql:
      use_pg_rewind: true

      parameters:
        max_connections: 500
        wal_level: replica
        max_wal_senders: 10
        max_replication_slots: 10
  initdb:
    - encoding: UTF8
    - data-checksums
  users:
    postgres:
      password: CHANGE_ME
      options:
        - superuser
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: NODE2-IP:5432

  data_dir: /var/lib/postgresql/16/main/
  bin_dir: /usr/lib/postgresql/16/bin/

  authentication:
    superuser:
      username: postgres
      password: CHANGE_ME

    replication:
      username: replicator
      password: CHANGE_ME

restapi:
  listen: 0.0.0.0:8008
  connect_address: NODE2-IP:8008

