scope: zabbix
namespace: /db/
name: node3

etcd3:
  host: NODE3-IP:2379

bootstrap:
  dcs:
    ttl: 30
    retry_timeout: 10

    postgresql:
      pg_hba:
          - host     replication     replicator  NODE1-IP/32     scram-sha-256
          - host     replication     replicator  NODE2-IP/32     scram-sha-256
          - host     replication     replicator  NODE3-IP/32     scram-sha-256
          - host     all     zabbix  NODE1-IP/32     scram-sha-256
          - host     all     zabbix  NODE2-IP/32     scram-sha-256
      use_pg_rewind: true
      parameters:
        max_connections: 500
        wal_level: replica
        max_wal_senders: 10
        max_replication_slots: 10
  initdb:
    - encoding: UTF8
    - data-checksums
  users:
    postgres:
      password: CHANGE_ME
      options:
        - superuser
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: NODE3-IP:5432

  data_dir: /var/lib/postgresql/16/main/
  bin_dir: /usr/lib/postgresql/16/bin/
  config_file: /etc/postgresql/16/main/postgresql.conf

  authentication:
    superuser:
      username: postgres
      password: CHANGE_ME

    replication:
      username: replicator
      password: CHANGE_ME

restapi:
  listen: 0.0.0.0:8008
  connect_address: NODE3-IP:8008

