DBHost=VIP-IP

DBName=zabbix

DBUser=zabbix

DBPassword=CHANGE_ME

DBPort=5432

HANodeName=zabbix-node2

NodeAddress=NODE1-IP:10051

CacheSize=512M

HistoryCacheSize=256M

HistoryIndexCacheSize=128M

TrendCacheSize=128M

ValueCacheSize=512M