ETCD_NAME="etcd-node2"

ETCD_DATA_DIR="/var/lib/etcd"

ETCD_INITIAL_ADVERTISE_PEER_URLS="http://NODE2-IP:2380"

ETCD_LISTEN_PEER_URLS="http://NODE2-IP:2380"

ETCD_LISTEN_CLIENT_URLS="http://NODE2-IP:2379,http://127.0.0.1:2379"

ETCD_ADVERTISE_CLIENT_URLS="http://NODE2-IP:2379"

ETCD_INITIAL_CLUSTER="etcd-node1=http://NODE1-IP:2380,etcd-node2=http://NODE2-IP:2380,etcd-node3=http://NODE3-IP:2380"

ETCD_INITIAL_CLUSTER_TOKEN="zabbix-etcd-cluster"

ETCD_INITIAL_CLUSTER_STATE="new"

