global_defs {
script_user root
enable_script_security
}

vrrp_script chk_postgresql {
script "/etc/keepalived/check_postgresql.sh"
interval 5
timeout 3
rise 2
fall 2
}

vrrp_instance VI_1 {
state MASTER
interface ens192

```
virtual_router_id 51

priority 100

advert_int 1

authentication {
    auth_type PASS
    auth_pass CHANGE_ME
}

virtual_ipaddress {
    VIP-IP/24
}

track_script {
    chk_postgresql
}
```

}
