#Add these lines to replicate
host     replication     replicator  NODE1-IP/32     scram-sha-256
host     replication     replicator  NODE2-IP/32     scram-sha-256
host     replication     replicator  NODE3-IP/32     scram-sha-256

host     all     zabbix  NODE1-IP/32     scram-sha-256
host     all     zabbix  NODE2-IP/32     scram-sha-256