listen_addresses='*'

max_connections=500

wal_level=replica

hot_standby=on

max_wal_senders=10

max_replication_slots=10

wal_keep_size=512MB

archive_mode=on

archive_command='true'

shared_buffers=2GB

effective_cache_size=6GB

maintenance_work_mem=512MB